### ISSUE TITLE
homebrewへのリリースを自動化する

### ISSUE THREAD

**Issue by mmmommm** [mmmommm/tenki#6]

**Comment by mmmommm** [comment]
- https://qiita.com/kcwebapply/items/4777dfc9151ebb3e8a19
- https://blog.monochromegane.com/blog/2014/05/19/homebrew-formula-for-golang/
- https://qiita.com/knqyf263

**Comment by mmmommm** [comment]
cp /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/tenki.rb ~/desktop/homebrew-tenki

**Comment by mmmommm** [comment]
github actions は公式がまだ解決できてないartifactのエラーがでてCIが回らないのでCIrcleCIに変更する
```
name: goreleaser

on:
  pull_request:
  push:

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
